//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBBliss
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_CHOICE
    {
        public int CHOICE_ID { get; set; }
        public string CHOICE_DESCRIPTION { get; set; }
        public int CHOICE_QUESTION_ID { get; set; }
        public int CHOICE_VOTES { get; set; }
    
        public virtual DT_QUESTION DT_QUESTION { get; set; }
    }
}
