//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBBliss
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_QUESTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DT_QUESTION()
        {
            this.DT_CHOICE = new HashSet<DT_CHOICE>();
        }
    
        public int QUESTION_ID { get; set; }
        public string QUESTION_DESCRIPTION { get; set; }
        public string QUESTION_IMG_URL { get; set; }
        public string QUESTION_THUMB_URL { get; set; }
        public System.DateTime QUESTION_PUBLISHED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DT_CHOICE> DT_CHOICE { get; set; }
    }
}
